// pages/index.tsx (for Pages Router)
// OR app/page.tsx (for App Router) - if using App Router, add 'use client';

// If using App Router (Next.js 13+ default) uncomment the line below:
'use client';

import Link from "next/link";

export default function Home() {
  return (
    <div style={{ background: '#fff', minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <div style={{ fontFamily: 'Arial, sans-serif', maxWidth: '600px', width: '100%', margin: '0 auto', padding: '20px', border: '1px solid #eee', borderRadius: '8px', boxShadow: '0 2px 4px rgba(0,0,0,0.1)' }}>
        <h2 style={{ textAlign: 'center', color: '#007BFF', fontSize: '28px', fontWeight: 'bold', marginBottom: '10px' }}>OpenAI GPT-4</h2>
        <h1 style={{ textAlign: 'center', color: '#333' }}>OpenAI 16-Bit Image Generator</h1>
        <p className="text-center mb-2 text-3xl font-bold text-blue-600">
          OpenAI AI
        </p>
        <div style={{ textAlign: 'center', marginBottom: '20px' }}>
          <p style={{ color: '#666' }}>
            Welcome! This is a 16x16 Image Generator powered by <b>OpenAI GPT-4</b>.<br/>
            The result is generated by OpenAI AI and is abstract—play with it for fun!
          </p>
        </div>
        <div style={{ textAlign: 'center', marginTop: '40px' }}>
          <h2 style={{ color: '#333', marginBottom: '10px' }}>How it works:</h2>
          <ul style={{ textAlign: 'left', color: '#666', lineHeight: '1.6' }}>
            <li>Type a description like "a yellow duck"</li>
            <li>Press Enter or click "Generate Pixel"</li>
            <li>The result is sometimes abstract and for entertainment purpose —see what OpenAI AI creates!</li>
          </ul>
        </div>
        <div style={{ textAlign: 'center', marginTop: '40px' }}>
          <Link href="/image-generator" style={{ 
            display: 'inline-block', 
            padding: '10px 20px', 
            backgroundColor: '#007BFF', 
            color: 'white', 
            textDecoration: 'none', 
            borderRadius: '5px',
            marginBottom: '20px'
          }}>
            🎨 Try 16x16 Image Generator
          </Link>
        </div>
      </div>
    </div>
  );
}